import type { PluginContracts } from "./types";
import { contractsSchemaId, contractsVersion } from "./version";

/**
 * KB Labs Commit Plugin - Contracts Manifest
 *
 * Level 2: Type-safe contracts with as const for type extraction.
 * Defines artifacts, commands, and their relationships.
 */
export const pluginContractsManifest = {
  schema: contractsSchemaId,
  pluginId: "@kb-labs/commit",
  contractsVersion,
  artifacts: {
    "commit.plan.json": {
      id: "commit.plan.json",
      kind: "json",
      description:
        "Current commit plan generated by LLM analysis of git changes.",
      pathPattern: ".kb/commit/current/plan.json",
      mediaType: "application/json",
      schemaRef: "@kb-labs/commit-contracts/schema#CommitPlan",
      example: {
        summary: "Example commit plan with two commits",
        payload: {
          schemaVersion: "1.0",
          commits: [
            {
              id: "c1",
              type: "feat",
              scope: "ui",
              message: "add button component",
              files: ["src/components/Button.tsx"],
              releaseHint: "minor",
            },
          ],
        },
      },
    },
    "commit.status.json": {
      id: "commit.status.json",
      kind: "json",
      description: "Git status snapshot at plan generation time.",
      pathPattern: ".kb/commit/current/status.json",
      mediaType: "application/json",
      schemaRef: "@kb-labs/commit-contracts/schema#GitStatusSnapshot",
    },
    "commit.history": {
      id: "commit.history",
      kind: "dir",
      description: "History of applied commit plans with results.",
      pathPattern: ".kb/commit/history/",
    },
  },
  commands: {
    commit: {
      id: "commit",
      description: "Generate and apply commits (default flow).",
      input: {
        ref: "@kb-labs/commit-contracts/schema#CommitRunInput",
        format: "zod",
      },
      output: {
        ref: "@kb-labs/commit-contracts/schema#CommitRunOutput",
        format: "zod",
      },
      produces: ["commit.plan.json", "commit.status.json"],
      examples: ["kb commit", "kb commit --dry-run", "kb commit --with-push"],
    },
    "commit:generate": {
      id: "commit:generate",
      description: "Generate commit plan from git changes using LLM.",
      input: {
        ref: "@kb-labs/commit-contracts/schema#GenerateInput",
        format: "zod",
      },
      output: {
        ref: "@kb-labs/commit-contracts/schema#GenerateOutput",
        format: "zod",
      },
      produces: ["commit.plan.json", "commit.status.json"],
      examples: [
        "kb commit generate",
        "kb commit generate --json",
        "kb commit generate --scope src/**",
      ],
    },
    "commit:apply": {
      id: "commit:apply",
      description: "Apply current commit plan (create local git commits).",
      input: {
        ref: "@kb-labs/commit-contracts/schema#ApplyInput",
        format: "zod",
      },
      output: {
        ref: "@kb-labs/commit-contracts/schema#ApplyOutput",
        format: "zod",
      },
      produces: [],
      examples: ["kb commit apply", "kb commit apply --force"],
    },
    "commit:push": {
      id: "commit:push",
      description: "Push commits to remote repository.",
      input: {
        ref: "@kb-labs/commit-contracts/schema#PushInput",
        format: "zod",
      },
      output: {
        ref: "@kb-labs/commit-contracts/schema#PushOutput",
        format: "zod",
      },
      produces: [],
      examples: ["kb commit push", "kb commit push --force"],
    },
    "commit:open": {
      id: "commit:open",
      description: "Show current commit plan.",
      input: {
        ref: "@kb-labs/commit-contracts/schema#OpenInput",
        format: "zod",
      },
      output: {
        ref: "@kb-labs/commit-contracts/schema#OpenOutput",
        format: "zod",
      },
      produces: [],
      examples: ["kb commit open", "kb commit open --json"],
    },
    "commit:reset": {
      id: "commit:reset",
      description: "Clear current commit plan.",
      output: {
        ref: "@kb-labs/commit-contracts/schema#ResetOutput",
        format: "zod",
      },
      produces: [],
      examples: ["kb commit reset"],
    },
  },
} as const satisfies PluginContracts;

// Extract types for use in manifest and commands
export type PluginArtifactIds = keyof typeof pluginContractsManifest.artifacts;
export type PluginCommandIds = keyof typeof pluginContractsManifest.commands;
